### ISSUE TITLE
Usage with `@nanostores/router`, type mismatch for `@useStores`

### ISSUE THREAD

**Issue by JulianCataldo** [emilbonnek/nanostores-lit#1]
First of all, thanks a lot for your fine work. Nanostores APIs are a real pleasure to use!

I've some observations regarding usage with router

<img width="724" alt="image" src="https://user-images.githubusercontent.com/603498/216036180-d601f976-aacf-47f6-b9ed-feaa0407b24a.png">

Same type mismatch for `router` and `searchParams`
```
<…> is missing the following properties from type 'WritableAtom<unknown>': set, notify
```

It still works perfectly though, despite typing errors.

I could make a "proxy/bridge/wrapper" regular atom maybe? But that would be just "cosmetical" without adding an actual feature.

**Comment by emilbonnek** [comment]
Hey @JulianCataldo!
Can I ask you to remake the issue at the new repo: https://github.com/nanostores/lit ?

I will try and see if I can resolve the types!

**Comment by JulianCataldo** [comment]
I didn't realised there was old repo, thought I was on the new one I'm used to, confounding them :o


Thank you for tackling this so fast! I will keep you in touch in case I encounter something else.

**Comment by emilbonnek** [comment]
Published new version to npm which fixes the type issue.
